redhat-plumbers/dracut-rhel9

.github/workflows/container.yml, .github/workflows/integration.yml, test/container/Dockerfile-CentOS-9-Stream, test/run-qemu, tools/test-github.sh
Note: I need to push the branch directly into the upstream repo, otherwise I wouldn't be able to access necessary tokens.
=> ci: bump C8 jobs to C9S

modules.d/95resume/module-setup.sh
This reverts commit 058ffa90669a4dbd2af16e025f22312408ed4ba9.
Resolves: #2017787
Fixes #
=> Revert "95resume: always install this module"

.github/workflows/differential-shellcheck.yml
Based on https://github.com/redhat-plumbers/dracut-rhel9/pull/28#issuecomment-1040214997
Related: #2050567
=> (#2050567) ci: Add Differential ShellCheck action

pkgbuild/dracut.spec
=> (#1947892) Do not use recommends for base packages

.github/workflows/differential-shellcheck.yml
differential-shellcheck@v2 uses SARIF format that drastically improves user experience.
Related: #2100440
=> (#2100440) ci: Use Differential ShellCheck action `v2`

.github/pull_request_template.md
=> ci: enhance pull request template

modules.d/06rngd/module-setup.sh, modules.d/06rngd/rngd.service, modules.d/06rngd/sysconfig
as there's no reason to keep a copy; there shouldn't be any modifications.
Resolves: #2181541
=> fix(rngd): install system service file

man/dracut.cmdline.7.asc, modules.d/95nvmf/module-setup.sh, modules.d/95nvmf/nbftroot.sh, modules.d/95nvmf/nvmf-autoconnect.sh, modules.d/95nvmf/parse-nvmf-boot-connections.sh
Cherry-picked commits:
9664e98b5db603567d42d4d0c6e6ea1bd3d5bf24
b3ff3f3fbce6878a754332cd4a05374e5e1156c8
a3cf4ec92202df43adf368c7fdd12e35d304a0e4
03921ec09e95ea49f89ae307dcca4e2e3d1bc6d6
e93e46520dd89a7357a15441ab6b141ff9ff9aeb
556ef46aa96650d72b2fd850a09fa04dff64bbb8
a93968b07567a654d18b8ef2144337d803186eca
a65fab69662d3adf52eb968411f59ebc5a173f7c
cf8986af7d9a3ce73f330de23d5312f924acea34
7c28e1148c086d8504caab6e70a1bcfda1bbf0b9
b03dc850e4630c3b727f71b853a1be588507a59e
0a4d7f9aece172f0f9a9286c94308b7e1ef8d500
Resolves: #1933787
_ _ _ _ _
Identical with current upstream repository state, except a refactoring patch (not changing any functionality).
=> (#1933787) feat(nvmf): NVMeoF support

dracut.sh, modules.d/06rngd/module-setup.sh, pkgbuild/dracut.spec
=> feat(spec): include modules for IMA

modules.d/01fips/module-setup.sh, modules.d/01fips/openssl.cnf
Resolves: #2176560
_ _ _ _
Original commit:
https://github.com/lnykryn/dracut/commit/5b2eaf2b7ffa9e0e2436d7a4fa81a8af30f30592
=> fix(fips): include openssl's fips.so and openssl.cnf

modules.d/95hwdb/module-setup.sh
=> fix(hwdb): fix formatting

pkgbuild/dracut.spec
and also move nvmf module to network subpackage.
Resolves: rhbz#1933787
=> fix(dracut.spec): add jq dependency to network subpackage

modules.d/00systemd/module-setup.sh
(cherry picked from commit 346e57c1b6af4e2cfdbaae64941f2f3b8454a944)
RHEL-only
Resolves: [RHEL-32853](https://issues.redhat.com/browse/RHEL-32853)
=> always include sg module

.github/advanced-commit-linter.yml, .github/auto-merge.yml, .github/pull-request-validator.yml, .github/tracker-validator.yml, .github/workflows/gather-metadata.yml, .github/workflows/source-git-automation-on-demand.yml, .github/workflows/source-git-automation.yml
- commit validation
- pull request validation
- tracker validation
- automatic merging
rhel-only
=> ci: enable source-git automation

test/container/Dockerfile-CentOS-9-Stream
=> test: fix url for btrfs-progs

Makefile, modules.d/01fips/module-setup.sh, modules.d/99openssl/module-setup.sh, modules.d/99openssl/openssl-check.sh, pkgbuild/dracut.spec, src/ossl/Makefile, src/ossl/src/ossl-config.c, src/ossl/src/ossl-files.c, src/ossl/tests/config/escapes.cnf, src/ossl/tests/config/escapes.cnf.expected, src/ossl/tests/config/included-file.noncnf, src/ossl/tests/config/includes.1.d/includes1.cnf, src/ossl/tests/config/includes.1.d/includes1.conf, src/ossl/tests/config/includes.1.d/nonconf.bak, src/ossl/tests/config/includes.2.d/main.cnf, src/ossl/tests/config/includes.2.d/subincludes.d/subconf.cnf, src/ossl/tests/config/includes.cnf, src/ossl/tests/config/includes.cnf.expected, src/ossl/tests/config/leading-and-trailing-whitespace.cnf, src/ossl/tests/config/leading-and-trailing-whitespace.cnf.expected, src/ossl/tests/config/order.cnf, src/ossl/tests/config/order.cnf.expected, src/ossl/tests/config/variables.cnf, src/ossl/tests/config/variables.cnf.expected, src/ossl/tests/files/engines.cnf, src/ossl/tests/files/engines.cnf.expected, src/ossl/tests/files/providers.cnf, src/ossl/tests/files/providers.cnf.expected, test/container/Dockerfile-CentOS-9-Stream
+ fix(openssl): harden ossl build CFLAGS
Resolves: RHEL-79815
=> (RHEL-79815) feat: add openssl module

install.d/51-dracut-rescue.install
=> (RHEL-53364) fix(rescue): copy hmac file for kernel

modules.d/35network-manager/module-setup.sh
[RHEL-69461](https://issues.redhat.com/browse/RHEL-69461)
Original issue:  RHEL-64754
=> (RHEL-69461) [RHEL-9.5] fix: RHEL-64754

dracut.sh, man/dracut.8.asc, shell-completion/bash/dracut
Resolves: RHEL-74399
Originial issue: RHEL-66582
=> (RHEL-74399) [RHEL-9.5] fix: RHEL-74399

.distro/backport_fix.sh
=> chore: sync the backport tool from rhel-10 source-git
