redhat-plumbers/dracut-rhel9

.github/workflows/container.yml
.github/workflows/integration.yml
.github/workflows/lint.yml

Otherwise the image push fails with permission error.
rhel-only
Related: #1966446
---
Note: pushing this directly into the org repo, otherwise I wouldn't be able to test the *privileged* actions.

ci: drop the hardcoded repo owner name

---

.github/workflows/container.yml
.github/workflows/integration.yml
test/container/Dockerfile-CentOS-8-Stream

The newly introduced Dockerfile contains a couple of FIXMEs, due to the current state of things, which we can hopefully drop soon (or after CentOS 8.5 release in case of the e2fsprogs* bug). Also, I had to disable some of the tests on C8S, since they require packages no longer present on RHEL/CentOS 8. Nevertheless, I left the Fedora job intact, which runs all the integration tests, so we still have a reasonable coverage here.
Note: again pushing directly into the org repo for correct GH Actions privileges.
\* I used my [CentOS CI repo](https://copr.fedorainfracloud.org/coprs/mrc0mmand/systemd-centos-ci-centos8/) with a newer e2fsprogs package to fix this, since I already use it in systemd CIs for the very same thing

ci: add a CentOS 8 Stream job

---

modules.d/35network-manager/nm-initrd.service

We get a nice warning about it being deprecated:
```
systemd-udev-settle.service is deprecated. Please fix nm-initrd.service not to pull it in.
```
The service is deprecated because its purpose was to wait for the
discovery of all hardware, but it didn't guarantee that (see the
systemd-udev-settle man page).
NM now runs as an independent service and can deal with devices showing
up at any point, but it does need udev to be started. For now just
Want/After systemd-udev-trigger.
(cherry picked from commit a0f12fb6a09b09f35ab28753d7c4461c10a8b562)
Resolves: #1970712
Fixes #

fix(network-manager): don't pull in systemd-udev-settle

---

modules.d/95resume/module-setup.sh

We can't always correctly decide if the resume module is needed.
So let's play safe and always include it.
see: https://github.com/dracutdevs/dracut/issues/924
RHEL-only
Resolves:#1926544
Fixes #

95resume: always install this module

---

modules.d/01fips/fips.sh
modules.d/01fips/module-setup.sh

On s390x, the `BOOT_IMAGE` karg injected by the bootloader is not a path
to the kernel image, but rather an integer describing the index of the
menu entry selected. Because of the way the s390x bootloader works,
there is no information retained about e.g. the path of the kernel that
was loaded.
This causes issues for the FIPS code which assumes that `BOOT_IMAGE` is
a path to the kernel image to derive the HMAC path. In non-OSTree
systems, this ends up working anyway, because the kernel is located at
the root of the boot partition.  In OSTree systems, this is not the
case. However, OSTree systems use BLS configs, and they are named in
reverse order of precedence (i.e. menu ordering). So from the
`BOOT_IMAGE` integer, we can figure out which BLS entry was selected.
Add some code to do just …

(#2050567) fix(fips): handle s390x OSTree systems

---

modules.d/95nfs/module-setup.sh

directory
The directory ownership for the statd directory should be
rpcuser:rpcuser.
Resolves: #2017846

(#2017846) 95nfs: set correct ownership and permissions for statd

---

dracut.sh

If file is not a regular file (test -f), dracut.sh fails,
which is unexpected change of behaviour.
The workaround would be to create an empty file.
Fixes: #1835
https://github.com/dracutdevs/dracut/issues/1835

fix(dracut.sh): do not fail on irregular files

---

modules.d/98dracut-systemd/dracut-emergency.sh
modules.d/98dracut-systemd/module-setup.sh
modules.d/99base/module-setup.sh

Partly reverts 32f68c1f9ac3720e8ce4b95a09c0ce680d5da786
In RHEL we don't want to have a password to log in into emergency mode.
RHEL-only
Resolves: #2057365
Fixes #

Partly revert "emergency mode: use sulogin"

---

modules.d/90kernel-modules/module-setup.sh

These drivers are needed to boot on some SoCs like NXP i.MX
We should include them so installation images will work.
(cherry picked from commit bc965cd8890013a6362733d217c18756134bbcdf)
Resolves: #2109498
Fixes #

fix(kernel-modules): always include nvmem driver on nvmem_on_arm

---

modules.d/50drm/module-setup.sh

Due to non-availability of Hyper-V video driver hyperv_drm in kdump
initramfs, the console seems to be in hang state with no text over it.
We should also go through the /sys/bus/vmbus/devices and include drivers
referenced there.
(cherry picked from commit 85149b85961aa535a3c61d492cd3594794e5cc3f)
Resolves: #2099502
Fixes #

fix(drm): add video drivers needed on hyper-v and similar

---

src/skipcpio/skipcpio.c

If lsinitrd is called from a context in which SIGPIPE is ignored (e.g.,
from a systemd unit with default setting of IgnoreSIGPIPE=), the
following line will result in an error being issued:
bin="$($SKIP "$image" | { read -r -N 6 bin && echo "$bin"; })"
An example error from `kdumpctl start` (which internally just calls
`systemctl start kdump.service`):
kdumpctl[1287]: ERROR: src/skipcpio/skipcpio.c:191:main(): fwrite
A minimal reproducer:
systemd-run -t sh -c '/path/to/skipcpio /path/to/any/file | false'
(cherry-picked from e9a4d73b73b716a9d2d5f01ceb7b427ef544ed9b)
Resolves: #2109803

fix(skipcpio): ignore broken pipe

---

modules.d/45url-lib/url-lib.sh

The redirection to stdout was originally added to workaround https://bugzilla.redhat.com/show_bug.cgi?id=989133 (curl would create no file if the source was empty), but I don't see that problem with current curl.
A nice side-effect of this change is that curl shows download progress.
(cherry picked from commit 1343d21d8c0d1f7239e27165e9c7633b504f777f)
Resolves: #2112475
<description/>
(cherry picked from commit ... )
Resolves: #

refactor(url-lib): write curl output directly to file

---

dracut-initramfs-restore.sh

The path detection is not working on latest Fedora and some other distros, and it fails to extract the initramfs. It seems the if statement is broken by a previous commit, so let's fix it.
Fixes: 3d8e1ad ('fix(dracut-initramfs-restore.sh): add missing default paths')
Signed-off-by: Kairui Song <kasong@tencent.com>
(cherry picked from commit 481b87fa7a82be54663071ad9ad76c34e378ddc7)
Resolves: #2149232
<description/>
(cherry picked from commit ... )
Resolves: #

fix(dracut-initramfs-restore.sh): initramfs detection not working

---

dracut-init.sh
dracut.sh
modules.d/99squash/module-setup.sh

Commit dc21638c3f0a fixes kdump kernel crash, due to non-conventional
library path in powerpc, by copying /etc/ld.so.cache under initdir.
While that works in general, it is vulnerable to failure because of
missing links, when the CPU is reconfigured to run in compatibility
mode of older CPU version. Avoid this by running ldconfig for squash
loader to create the necessary links & ld cache for it. Doing this
also saves a few kilobyes of space as the copied ld cache is bigger
in size than the one needed for squash loader environment.
Fixes: dc21638c3f0a ("fix(squash): keep ld cache under initdir")
Cc: Pingfan Liu <piliu@redhat.com>
Signed-off-by: Hari Bathini <hbathini@linux.ibm.com>
Resolves: rhbz#2122274
_ _ _ _ 
Not merged upstream yet.

fix(squash): build ld cache for squash loader

---

modules.d/80lvmthinpool-monitor/start-thinpool-monitor.sh

The state of lvm thin pool may change into inactived state when kdump into 2nd kernel. As a result, lvextend will fail to extend its size. For example:
In 1st kernel:
$ lvs
LV       VG         Attr       LSize   Pool     Origin Data%  Meta%
vol      vg00       Vwi-a-tz-- 300.00m thinpool        70.54
thinpool vg00       twi-aotz-- 236.00m                 89.67  12.50
...
In 2nd kernel:
LV       VG         Attr       LSize   Pool     Origin Data%  Meta%
vol      vg00       Vwi-aotz-- 300.00m thinpool        70.54
thinpool vg00       twi---tz-- 236.00m                 89.67  12.50
...
And the lvextend failing log:
[  8.483878] start-thinpool-monitor[590]: lvextend using policy requires the thin pool to be active.
In this patch, we will first activate lvm thin pool before calling lvextend …

(#2175096) fix(lvmthinpool-monitor): activate lvm thin pool before extend its size

---

dracut-functions.sh
dracut.sh

- fix(dracut.sh): use dynamically uefi's sections offset
- fix(dracut.sh): handle imagebase for uefi
Resolves: #2180787

(#2180787) Dynamically calculate UEFI sections offset

---

modules.d/98integrity/evm-enable.sh

Track when a key is successfully loaded, and return 1 if no key has been loaded.  This will not enable EVM if there are no keys available in the system.
Fix #1847
Signed-off-by: Alberto Planas <aplanas@suse.com>
Related: #2158155
(Cherry-picked commit: 90585c624af15ba0abb7f32b0c2afc2b122dd019)
_ _ _ _ 
Additional fix. Only significant (non code-style related) difference from upstream.

fix(integrity): do not enable EVM if there is no key

---

modules.d/95hwdb/module-setup.sh
pkgbuild/dracut.spec

Adding a module to install hwdb. Further extensions might make only selected part of hwdb installable, to save space. The module is not included by default.
Including the module adds 2MB of compressed data (on Fedora, the file has 12MB).
hwdb is needed in case of custom HW, like a keyboard/mouse or various interfaces.
Original PR: https://github.com/dracutdevs/dracut/pull/1681
(Cherry-picked commit: 062e739d89543a38d4b3e2cab155912bc4bf9e56)
Resolves: #2233597
_ _ _ _ 
Clone for https://github.com/redhat-plumbers/dracut-rhel8/commit/62fb051db129a1cbb5645107933e961a57d8bef3

feat(hwdb): install hwdb on demand when module is needed

---

dracut.sh
modules.d/01systemd-networkd/module-setup.sh
modules.d/01systemd-timesyncd/module-setup.sh
modules.d/35network-legacy/module-setup.sh
modules.d/35network-manager/module-setup.sh

systemdsystemconfdir usually expands to /etc/systemd/system, but the local configuration of systemd-networkd, systemd-timesyncd, portablectl and systemd users is saved into directories whose parent is /etc/systemd (systemdutilconfdir).
Also add missing exports.
fix(network-legacy): correct wrong local network configuration path
fix(network-manager): correct wrong local network configuration path
refactor(systemd-networkd): use more precise global variables
refactor(systemd-timesyncd): use more precise global variables
refactor(network-legacy): use more precise global variables
refactor(network-manager): use more precise global variables
(Cherry-picked commits:
ae4c8744dc3dbceb142c6eb88fd69bc6aaf29e20
a60543bf9746022e4430d310892ee03bb837b6a2
cb39aec479bdabfa7b1af5168c14ca5683905a7d …

fix(dracut.sh): correct wrong systemd variable paths

---

modules.d/95nvmf/module-setup.sh

When creating initramfs for universal boot image such as an installer, we can't include any machine-specific IDs. Let's move the check for /etc/nvme/hostnqn and /etc/nvme/hostid files presence to the hostonly section to avoid unsatisfied requirements.
Signed-off-by: Tomas Bzatek <tbzatek@redhat.com>
(Cherry-picked commit: 1cf10397b5f002790a096e5bdce733436fffbd2d
PR: https://github.com/dracutdevs/dracut/pull/2523)
Resolves: RHEL-3630

fix(nvmf): move /etc/nvme/host{nqn,id} requirement to hostonly

---

dracut.sh
man/dracut.8.asc
man/dracut.conf.5.asc
shell-completion/bash/dracut

Take existing .sbat section from the uefi stub and merge it with vmlinux .sbat (if it exists) and user-provided .sbat parameters using the new --sbat option.
For some reasons, --update-section in objcopy does not resize the .sbat section, so remove the section from the stub and add it to the UKI as new one, to avoid having incomplete SBAT strings.
Signed-off-by: Emanuele Giuseppe Esposito <eesposit@redhat.com>
(Cherry-picked commit: 550a0084fd95870f35218dc2cf8ea91fde1c728a)
Resolves: RHEL-5732

feat(dracut): add --sbat option to add sbat policy to UKI

---

modules.d/00systemd/module-setup.sh

systemd-sysroot-fstab-check is a symlink to systemd-fstab-generator added in systemd commit https://github.com/systemd/systemd/commit/cd7ad0cb
(cherry picked from commit 23684e4a2bb024595ad63d9f49d83b4693537110)
Resolves: RHEL-12409

feat(systemd): install systemd-sysroot-fstab-check

---

modules.d/95fcoe-uefi/parse-uefifcoe.sh

Exit early in case get_fcoe_boot_vlan exits with error or just an empty string, instead of producing invalid config entry.
(Cherry-picked commit: 45fc8df1cf3fdf9726efda4d26c7cccb9e6aedd2
PR: https://github.com/dracutdevs/dracut/pull/2379)
Resolves: RHEL-14251

fix(fcoe-uefi): exit early on empty vlan

---

src/install/dracut-install.c

in install_dependent_modules we use &path[kerneldirlen] as the key for inserting, let's do the same for checking.
otherwise installing kernel module has circular dependency from a custom kernel module directory will cause infinite recursion and segfault.
$ grep ipmi kbuilt/lib/modules/5.10.121/modules.dep kernel/drivers/char/ipmi/ipmi_msghandler.ko:
kernel/drivers/char/ipmi/ipmi_devintf.ko: kernel/drivers/char/ipmi/ipmi_msghandler.ko
$ grep ipmi kbuilt/lib/modules/5.10.121/modules.softdep softdep ipmi_msghandler post: ipmi_devintf
$ ./dracut-install -D /tmp --kerneldir ~/working/kernel/linux-5.10.121/kbuilt/lib/modules/5.10.121 -m ipmi-devintf Segmentation fault (core dumped)
(gdb) b install_dependent_modules
Breakpoint 1 at 0x7db0: file src/install/dracut-install.c, line 1513. (gdb) bt …

fix(dracut-install): use stripped kernel module path as hash key

---

modules.d/00systemd/module-setup.sh
test/TEST-01-BASIC/test.sh
test/TEST-03-USR-MOUNT/test.sh
test/TEST-20-NFS/test.sh
test/TEST-50-MULTINIC/test.sh
test/TEST-60-BONDBRIDGEVLANIFCFG/test.sh
test/TEST-63-DRACUT-CPIO/test.sh

In [0] systemd gained a new binary - systemd-executor - that's used to spawn processes forked off systemd. Let's copy it into the initrd if it's available.
[0] https://github.com/systemd/systemd/pull/27890
(cherry picked from commit bee1c4824a8cd47ce6c01892a548bdc07b1fa678)
Related: RHEL-30581
---
Similarly to https://github.com/redhat-plumbers/dracut-rhel9/pull/72 this is a no-op in RHEL, since systemd there doesn't yet have the sd-executor stuff, but it'll make my life much easier in upstream CIs.

feat(systemd): install systemd-executor

---

modules.d/01fips/module-setup.sh

Random device nodes were required to workaround libgcrypt initialization
problem (see https://bugzilla.redhat.com/show_bug.cgi?id=1401444) which
is gone since libgcrypt-1.10 (2022): modern Linux kernels (3.17+) support
getrandom() syscall and libgcrypt has switch to using getentropy()
(glibc-2.25+).
The requirement to run dracut as root (which is needed to mknod
/dev/{random,urandom}) is a particular problem for building UKIs in distro
build systems where packages are not built by a privileged user.
Note, dracut itself always pre-creates /dev/{null,kmsg,console,random,urandom}
devices when running privileged so the patch has no effect on 'traditional'
setup.
Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>
(Cherry-picked commit: 62f907e9eb3147ad8603953ec3cf29673d4fae79)
Resolves: …

fix(fips): remove /dev/{random,urandom} pre-creation

---

modules.d/01fips/fips-boot.sh
modules.d/01fips/fips-load-crypto.sh
modules.d/01fips/fips-noboot.sh
modules.d/01fips/fips.sh
modules.d/01fips/module-setup.sh

The `mount_boot` method called from fips-noboot.sh in the pre-pivot hook blindly
executes `rm -rf /boot` if there is no `boot=` command line parameter, without
first checking that /boot is not already mounted by other means.
feat(fips): add progress messages
This allows to better understand at what point a FIPS integrity test failed.
Signed-off-by: Raymund Will <rw@suse.com>
fix(fips): only unmount /boot if it was mounted by the fips module
The `do_fips` method should only unmount /boot if it was mounted in the
`mount_boot` method.
In addition, now the `mount_boot` method checks if /boot is already mounted.
Signed-off-by: Raymund Will <rw@suse.com>
fix(fips): move fips-boot script to pre-pivot
This is needed in s390x to be able to use the same `boot=` command line
parameter in grub and …

fix(fips): do not blindly remove /boot

---

.github/labeler.yml
.github/tracker-validator.yml
.github/workflows/source-git-automation-on-demand.yml
.github/workflows/source-git-automation.yml

Since we are using `actions/labeler@main`, its format changed, displaying the following error with every new PR:
```
Run actions/labeler@main
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Error: Error: found unexpected type for label 'repository' (should be array of config options)
Error: found unexpected type for label 'repository' (should be array of config options)
```
(cherry picked from commit de8ac6300d115a05d467dbb6b9a7c2599a2d306f)

(RHEL-30581) fix(github): update format of labeler

---

.github/labeler.yml

(cherry picked from commit 1d60dd74ee721f17cdaadd56b874b564b89c0145)
Related: RHEL-30581
follow-up to https://github.com/redhat-plumbers/dracut-rhel9/pull/81

(RHEL-30581) ci: remove non-existing modules from labeler

---

modules.d/35network-manager/nm-initrd.service

During shutdown, there is no ordering dependency between the nm-initrd service
and the D-Bus daemon, and so the latter can be stopped before. This causes
issues to NetworkManager, especially when team interfaces are present because
NM will see teamd dropping from the bus and will try to reactivate the
connection.
Add a "After" dependency to make sure the D-Bus daemon is stopped after NM on
shutdown.
(Cherry-picked commit: 1b7d83110741560f26027fbd9435763eef56935a)
Resolves: RHEL-13192

(RHEL-13192) fix(network-manager): add "After" dependency on dbus.service

---

modules.d/45url-lib/url-lib.sh
test/TEST-20-NFS/client-init.sh
test/TEST-20-NFS/test.sh

nfs_already_mounted() doesn't work when the installation ISO and kickstart file on a same NFS share are specified with inst.repo and inst.ks boot parameter as below.
inst.repo=nfs:192.168.1.1:/home/data/rhel9.iso inst.ks=nfs:192.168.1.1:/home/data/ks.cfg
NOTE: /home/data is configured for nfs share on 192.168.1.1
One problem is a file (not a directory) was passed into nfs_already_mounted().
nfs_already_mounted() is the function to judge if the given directory is already mounted.
So, filepath should be passed in nfs_fetch_url().
The other problem is about the trailing slash in the nfs path in /proc/mounts.
The /proc/mounts has an entry after nfs mount of inst.repo.
192.168.1.1:/data/   /run/install/isodir  nfs  ro,relatime,<snip>
In this case, nfs_already_mounted() returns …

(RHEL-13193) fix(url-lib.sh): nfs_already_mounted() with trailing slash in nfs path

---

modules.d/01systemd-pcrphase/module-setup.sh
pkgbuild/dracut.spec

Introducing the systemd-pcrphase module
(Cherry-picked commit: c4c595ceeab79fefde74750ec6b0d15d7d16ede6)
Resolves: RHEL-27944

(RHEL-27944) feat(systemd-pcrphase): introducing the systemd-pcrphase module

---

modules.d/95nfs/module-setup.sh

as those paths are used by bootc instead of the /etc ones.
(cherry picked from commit 45cdf3c4f24f77f04b264a7747f115d1031b2e67)
Resolves: RHEL-52326

(RHEL-52326) fix(nfs): include also entries from /usr/lib/{passwd,group}

---

modules.d/00systemd/module-setup.sh

(cherry picked from commit 455dbb585583bd2e1d40ebb61c335a2ad6dff053)
Resolves: RHEL-53114

(RHEL-53114) fix(systemd): set right permissions for the machine-id file

---

lsinitrd.sh

Introduce new path for lsinitrd.sh to look into:
/usr/lib/modules/$kver/initramfs.img
Which is valid on all ostree-based systems, and also other image based
systems with pre-generated initramfs.
Ref: https://issues.redhat.com/browse/RHEL-35890
(cherry picked from commit 7c7cdd9317c21b19a0393f5d28d1acb7ee3ff027 from PR#582)
Resolves: RHEL-35890

(RHEL-35890) feat(lsinitrd.sh): look for initrd in /usr/lib/modules/

---

dracut-init.sh

This gives precedence of force_add_dracutmodules to omit_dracutmodules,
as there is not other way to override omit_dracutmodules list, and users
would expect it to be overriden from command line.
Ref: https://github.com/dracut-ng/dracut-ng/pull/569
This way, `--add` retains it behaviour, and `--force-add` gains additional
functionality in non-hostonly mode. The module may still be skipped
if the module check returns 1, but it should throw error (as I'd expect
for `--force-add`).
Ref: https://issues.redhat.com/browse/RHEL-26114
(cherry picked from commit a669346f48cbb3278c51ba5e95b1b91f9bfdee0a)
Resolves: RHEL-26114

(RHEL-26114) feat(dracut-init.sh): give --force-add precedence over --omit

---

modules.d/35network-manager/module-setup.sh

- fix(35network-manager): install nftables kernel modules needed
- fix(35network-manager): install nft binary during module installation
Resolves: RHEL-64754

(RHEL-64754) fix(35network-manager): install nft binary during module installation

---

src/install/dracut-install.c

When use clone ioctl to copy a file, the extended attributes of files are
missing, which is inconsistent with the result by using the cp command.
This commit add the process to copy extended attributes after clone_file().
Signed-off-by: Huaxin Lu <luhuaxin1@huawei.com>
(cherry picked from commit 1cf0db26e43fe4c6173acdb8047f16666ebf070a)
Resolves: RHEL-55245

(RHEL-55245) fix(dracut-install): copy xattr when use clone ioctl

---

dracut.sh
man/dracut.8.asc
shell-completion/bash/dracut

When generating kdump's initrd, we want to keep [omit_]dracutmodules
empty and let kdump to handle the modules. And we don't want to
affect the first kernel's initrd, so we cannot place our conf file
to /etc/dracut.conf.d or /usr/lib/dracut/dracut.conf.d.
This patch adds a new option to allow user to add an extra configuration
directory to use *.conf files from. If the dir not exists, will look for
confdir's subdir.
After that, kdump can use "--add-confdir kdump" if
/usr/lib/dracut/dracut.conf.d/kdump exists, to apply its own dracut conf.
See also:
https://github.com/rhkdump/kdump-utils/issues/11
https://github.com/rhkdump/kdump-utils/pull/31
Suggested-by: Dave Young <dyoung@redhat.com>
Signed-off-by: Lichen Liu <lichliu@redhat.com>
(cherry picked from commit …

(RHEL-66582) feat(dracut.sh): add --add-confdir option

---

modules.d/01fips/fips.sh
modules.d/01fips/module-setup.sh

Kernel integrity check in FIPS module is incompatible with UKIs as neither
/boot/vmlinuz-`uname-r` nor /boot/.vmlinuz-`uname-r`.hmac are present. UKI
is placed to $ESP\EFI\Linux\<install-tag>-<uname-r>.efi and if a .hmac file
is present next to it, it is possible to do similar check.
Note, UKIs have a 'one size fits all' command line and 'boot=' is not expected
to be set. Luckily, if the UKI is systemd-stub based then we can expect
'LoaderDevicePartUUID' variable containing PARTUUID of the ESP to be set. Mount
it to /boot using the existing logic.
Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>
(cherry picked from commit 72684ff519be4f29c45cbb0f84759e645b0ac4be)
Resolves: RHEL-56885

(RHEL-56885) feat(fips): add support for UKIs

---

dracut-functions.sh

- **fix(kernel-modules): use modalias info in get_dev_module()**
- **fix(dracut-functions.sh): convert mmcblk to the real kernel module name**

(RHEL-55708) rhel 9 fix 55708

---

modules.d/35network-manager/module-setup.sh

Issue introduced in commit: 0a264651d148b543c0c5d6b0a07909cdcb1abfba
Resolves: RHEL-64754

(RHEL-64754) fix(35network-manager): remove duplicate installkernel function

---

.github/workflows/gather-metadata.yml

as v3 is deprecated.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
rhel-only

ci: bump actions/upload-artifact version to v4

---

modules.d/01fips/module-setup.sh

rhel-only
Resolves: RHEL-53364

(RHEL-53364) feat(fips): include fips module unconditionally

---

dracut.sh
test/TEST-01-BASIC/test.sh

Modify the basic test case to use --omit-drivers and make it fail
without the PR and make it pass with the PR.
The test would fail with the following error without the PR:
FATAL: iscsiroot requested but kernel/initrd does not support iscsi
(cherry picked from commit a7f5cdbccbbd4d8c406ea7c4b3e6f25cd747e648)
Resolves: RHEL-57094

(RHEL-57094) fix(dracut.sh): make omit-drivers option do exact match for names

---

.github/workflows/gather-metadata.yml
.packit.yml
dracut-functions.sh

https://issues.redhat.com/browse/RHEL-79790

Rhel 9.5 fix 79790

---

.distro/backport_fix.sh
.github/workflows/differential-shellcheck.yml

chore: sync backport tool with rawhide

---

dracut.sh

That causes dropindirs_sort() to look for .conf files in / due to
expansion:
for d in "$@"; do
for i in "$d/"*"$suffix"; do
Fixes #1275
(cherry picked from commit 000cfa0c278c0858e81c8dd2ff7231f069f0afb1)
Resolves: RHEL-92584

(RHEL-92584) fix(dracut.sh): don't pass empty string as dir

---

.distro/backport_fix.sh
modules.d/00systemd/module-setup.sh

sys-kernel-config.mount needs modprobe@configfs.service since systemd v246.7
(https://github.com/systemd/systemd/commit/42cc2855), so the kernel configfs
fails to mount in the initrd.
(cherry picked from commit 928252a145ca44627ba5873e01245eabe246992f)
Resolves: RHEL-97169

(RHEL-97169) fix(systemd): add missing modprobe@.service

---

dracut-functions.sh
modules.d/95nvmf/module-setup.sh
modules.d/95nvmf/parse-nvmf-boot-connections.sh

Currently check_vol_slaves_all return 0 even after checks on all slaves
fail. And this leads to an issue that "dracut -hostonly-mode strict"
gets stuck forever because instmods keeps waiting for user input when
it's passed empty argument in the kernel-modules module.
Fixes: c7c8c498 ("dracut-functions.sh: catch all lvm slaves")
Reported-by: Tomáš Bžatek <tbzatek@redhat.com>
Signed-off-by: Coiby Xu <coxu@redhat.com>
(cherry picked from commit 1fcfb2bffdad22873a804043eeeb9bb65a99caa8)
Resolves: RHEL-104222

(RHEL-104222) fix: let check_vol_slaves_all return 1 when checks on all slaves fail

---

dracut.sh

- **refactor(dracut): introduce clamp_mtimes helper function**
- **fix(dracut): ensure hardlink deduplication is reproducible**

(RHEL-101901) rhel 9 fix 101901
